#  ____  ____  ____  ____  _____ ____  ____  ____  ____  ____
# / ___\/   _\/  _ \/  __\/  __//  _ \/  _ \/  _ \/  __\/  _ \
# |    \|  /  | / \||  \/||  \  | | //| / \|| / \||  \/|| | \|
# \___ ||  \_ | \_/||    /|  /_ | |_\\| \_/|| |-|||    /| |_/|
# \____/\____/\____/\_/\_\\____\\____/\____/\_/ \|\_/\_\\____/
#
# Scoreboard-r by Rien Bijl
# rep: github : RienBijl/Scoreboard-revision
# v: 1.4.2 RELEASE

settings:
  # Safe-mode determines if scoreboard is synchronized with the server (true) or asynchronized (false)
  # Synchronized (safe-mode: true) is more stable and robust
  # Asynchronized (safe-mode: false) is more faster but can cause strange problems in some cases
  safe-mode: true 
  # If the server version is 1.13 or higher, enable longline.
  # true: you can use 128 characters per line (1.13 and up)
  # false: you can use 32 characters per line (1.12 and down)
  longline: true

# In what worlds should we disable scoreboard?
disabled-worlds:
  - 'non_existant_world'

board:
  title:
    liner:
      - '&4> &c&lScoreboard &4<'
  rows:
    1:
      interval: 5
      liner:
      - '&c------------------------'
      - '&4------------------------'
    2:
      interval: 80
      liner:
      - '&cPlayer:'
    3:
      interval: 80
      liner:
      - '%player_name%''
    4:
      interval: 80
      liner:
      - ''
    5:
      interval: 80
      liner:
      - '&cPing:'
    6:
      interval: 5
      liner:
      - '%player_ping% ms'
    7:
      interval: 80
      liner:
      - ''
    '8':
      interval: 80
      liner:
      - ''
    '9':
      interval: 20
      liner:
      - ''
    10:
      interval: 80
      liner:
      - '&4Time: &f%player_world_time_24%'
    11:
      interval: 80
      liner:
      - '&4X: &f%player_x% &4Y: &f%player_y% &4Z: &f%player_z%'
    12:
      interval: 80
      liner:
      - '%player_health_scale%'
    50:
      interval: 5
      liner:
      - '&c------------------------'
      - '&4------------------------'
